In [2]:
# 1-Dim
import numpy as np
x=np.array([1,2,3,4,5,8])
print(x)
print(x.ndim) # 1 dimensional array
print(x.shape)

[1 2 3 4 5 8]
1
(6,)


In [3]:
x

array([1, 2, 3, 4, 5])

# 0-D

In [7]:
# 0-Dim
x2=np.array(1)
print(x2)
print(x2.ndim)  # 0 dimensional
print(type(x2))

1
0
<class 'numpy.ndarray'>


# 2-D

In [24]:
# 2-Dim
l=[[1,2,3,57],[4,5,6,67],[7,8,9,77]]
z=np.array(l)
print(z)
print(z.ndim)  # 2 dimensional
print(z.shape) #(row,col)
print(f"no of rows:{z.shape[0]} and no of col:{z.shape[1]}")
print(z[0:,2])
print("------------------------------")
print(z[0,0:])
print("------------------------------")
print(z[0:,0::2])
print("------------------------------")
print(z[0:2,1::2])
print("------------------------------")
print(z[1::,0:2])

[[ 1  2  3 57]
 [ 4  5  6 67]
 [ 7  8  9 77]]
2
(3, 4)
no of rows:3 and no of col:4
[3 6 9]
------------------------------
[ 1  2  3 57]
------------------------------
[[1 3]
 [4 6]
 [7 9]]
------------------------------
[[ 2 57]
 [ 5 67]]
------------------------------
[[4 5]
 [7 8]]


In [13]:
l=[[1,2,3,44],[4,5,6,45],[7,8,9],[10,11,12]]
z=np.array(l)
print(z)

[list([1, 2, 3, 44]) list([4, 5, 6, 45]) list([7, 8, 9])
 list([10, 11, 12])]
1


<ipython-input-13-74f9c53e1a58>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  z=np.array(l)


# 3-D

In [ ]:
# 3-Dim
z=[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[11,22,33],[44,55,66],[77,88,99],[100,110,120]]]
z1=np.array(z)
print(z1)
print("------------------------------")
print(z1.ndim) # 3 Dimensional array
print("------------------------------")
print(z1.shape) #(no of 2-d arr,row,col)
print("------------------------------")
print(z1[0,1,2]) 
print("------------------------------")
print(z1[1,1,2])
print("------------------------------")
print(z1[0,2,0:])
print("------------------------------")
print(z1[0,0:,-1])
print("------------------------------")
print(z1[0])
print("------------------------------")
print(z1[0:,0::2,0::2])

# Reshaping

In [43]:
import numpy as np
z=np.arange(1,101)
x=np.array(z)
print(x.shape)
print("------------------------------")
# convert 1-d to 2-d
ans1=x.reshape(20,5) #(r,c)
print(ans1)
print(ans1.shape)
print("------------------------------")
ans2=x.reshape(25,-1) #(r,c) (25,unknown) unknown=-1
print(ans2)
print(ans2.shape)
print("------------------------------")

(100,)
------------------------------
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]
(20, 5)
------------------------------
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]
 [ 21  22  23  24]
 [ 25  26  27  28]
 [ 29  30  31  32]
 [ 33  34  35  36]
 [ 37  38  39  40]
 [ 41  42  43  44]
 [ 45  46  47  48]
 [ 49  50  51  52]
 [ 53  54  55  56]
 [ 57  58  59  60]
 [ 61  62  63  64]
 [ 65  66  67  68]
 [ 69  70  71  72]
 [ 73  74  75  76]
 [ 77  78  79  80]
 [ 81  82  83  84]
 [ 85  86  87  88]
 [ 89  90  91  92]
 [ 93  94  95  96]
 [ 97 

In [44]:
# convert 1-d to 3-d
ans1=x.reshape(2,2,25)
print(ans1)
print(ans1.shape)

[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20  21  22  23  24  25]
  [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
    43  44  45  46  47  48  49  50]]

 [[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
    68  69  70  71  72  73  74  75]
  [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
    93  94  95  96  97  98  99 100]]]
(2, 2, 25)


# Concatenate

In [50]:
x=np.arange(1,10)
y=np.arange(11,20)
a1=np.array(x).reshape(3,3)
a2=np.array(y).reshape(3,3)
print(a1)
print("------------------------------")
print(a2)
print("------------------------------")
z=np.concatenate((a1,a2),axis=0) #  adding row wise      axis=0 is by default
print(z)
print("------------------------------")
z1=np.concatenate((a1,a2),axis=1) #  adding col wise
print(z1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
[[11 12 13]
 [14 15 16]
 [17 18 19]]
------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
------------------------------
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


# Array split

In [51]:
# 1-D
x=np.arange(1,11)
z1=np.array(x)
print(z1)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
np.array_split(z1,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [53]:
np.array_split(z1,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [56]:
np.array_split(z1,6)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10])]

In [57]:
np.array_split(z1,7)

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7]),
 array([8]),
 array([9]),
 array([10])]

In [59]:
np.array_split(z1,11)

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([], dtype=int32)]

In [ ]:
# 2-D(array split)

In [60]:
l1=[[1,2,3,57],[4,5,6,67],[7,8,9,77]]
x2=np.array(l1)
print(x2)

[[ 1  2  3 57]
 [ 4  5  6 67]
 [ 7  8  9 77]]


In [61]:
np.array_split(x2,2)

[array([[ 1,  2,  3, 57],
        [ 4,  5,  6, 67]]),
 array([[ 7,  8,  9, 77]])]

# where

In [66]:
l1=[2,5,22,45,56,23,11,23,6,18,19,35]
x1=np.array(l1)
print(x1)

[ 2  5 22 45 56 23 11 23  6 18 19 35]


In [65]:
np.where(x1>40) # return index

(array([3, 4], dtype=int64),)

In [67]:
np.where(x1%2==0,"Even","Odd")

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Odd', 'Odd', 'Even',
       'Even', 'Odd', 'Odd'], dtype='<U4')

#  sorting

In [78]:
l2=[[1,21,3,5],[41,5,1,67],[71,8,91,77]]
x2=np.array(l2)
print(x2)

[[ 1 21  3  5]
 [41  5  1 67]
 [71  8 91 77]]


In [80]:
np.sort(x2)  # axis=1 row wise sort by default

array([[ 1,  3,  5, 21],
       [ 1,  5, 41, 67],
       [ 8, 71, 77, 91]])

In [79]:
np.sort(x2,axis=0) # axis=0 col wise

array([[ 1,  5,  1,  5],
       [41,  8,  3, 67],
       [71, 21, 91, 77]])